// <auto-generated />
namespace PAA_MVC_2021.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConfirmedAddCanBeNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfirmedAddCanBeNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202107130119464_ConfirmedAddCanBeNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
